models/Rechadminencad.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "rech_admin_encad".
 *
 * @property integer $rae_type
 * @property integer $cont_id
 *
 * @property Contact $contact
 */
class Rechadminencad extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rech_admin_encad';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rae_type'], 'required'],
            [['cont_id','rae_type'], 'integer'],
            [['cont_id'], 'exist', 'skipOnError' => true, 'targetClass' => Contact::className(), 'targetAttribute' => ['cont_id' => 'cont_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'rae_type' => 'Type de contact',
            'cont_id' => 'Cont ID',
            /* related attributes*/
            'contactNom' => 'Nom',
            'contactPrenom' => 'Prénom',
            'contactGSMPrincipal' => 'Numéro GSM',
            'contactEmailPrincipal' => 'E-mail'
        ];
    }
    
    public function beforeDelete() {
        \rmrevin\yii\module\Comments\models\Comment::deleteAll(['entity' => 'rea-'.$this->cont_id]);
        Appartenir::deleteAll(['cont_id' => $this->cont_id]);
        return parent::beforeDelete();
    }

    public function afterDelete() {
        Contact::findOne($this->cont_id)->delete();
        return parent::afterDelete();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContact()
    {
        return $this->hasOne(Contact::className(), ['cont_id' => 'cont_id']);
    }
    
      /* Getter for contact nom */
    public function getContactNom() {
        return $this->contact->cont_nom;
    }
    
    /* Getter for contact prenom */
    public function getContactPrenom() {
        return $this->contact->cont_prenom;
    }
    

    public function getContactCivilite() {
        return $this->contact->cont_civilite;
    }
    
    public function getContactGSMPrincipal() {
        return $this->contact->cont_gsm_principal;
    }
    
    public function getContactEmailPrincipal() {
        return $this->contact->cont_email_principal;
    }
    
    public function getContactAnneeNaissance() {
        return $this->contact->cont_annee_naissance;
    }
    public function getContactCreatedAt() {
        return $this->contact->cont_annee_naissance;
    }
    
    
    public function getSecteurs()
    {
        return $this->hasMany(Secteur::className(), ['sect_id' => 'sect_id'])->viaTable('travailler', ['cont_id' => 'cont_id']);
    }
    
//    public function setSecteurs($v)
//    {     
//        $this->secteurs = $v;
//    }
    
    public function getSecteursID() {
        if($this->secteurs == null) return null;
        return $this->secteurs->sect_id;
    }
}

controllers/RechadminencadController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Rechadminencad;
use app\models\RechadminencadSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RechAdminEncadController implements the CRUD actions for RechAdminEncad model.
 */
class RechadminencadController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all RechAdminEncad models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RechAdminEncadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionSearch() {
        return $this->actionIndex();
    }

    /**
     * Displays a single RechAdminEncad model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new RechAdminEncad model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new RechAdminEncad();
        $contactModel = new \app\models\Contact();
        $post = Yii::$app->request->post();
        
        if ($contactModel->load($post) && $model->load($post)) {
            if ($contactModel->alreadyExists()) {
                if (!isset($post['forceadd'])) {
                    Yii::$app->session->setFlash('error', "Ce contact existe déjà !");
                    return $this->render('create', [
                                'model' => $model,
                                'contactModel' => $contactModel,
                    ]);
                }
            }
            $contactModel->cont_created_at = date("Y-m-d H:i:s");

            if ($model->validate() && $contactModel->save()) { //validate $model BEFORE saving $contactModel
                $model->cont_id = $contactModel->cont_id;
                if ($model->save(false)){ // save(false) bypass validation (already did 2 lines ago)
                    return $this->redirect(['view', 'id' => $contactModel->cont_id]);
                }
            } else {
                throw new \yii\base\ErrorException;
            }
        } else {
            return $this->render('create', [
                'model' => $model,
                'contactModel' => $contactModel,
            ]);
        }
    }

    /**
     * Updates an existing RechAdminEncad model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $contactModel = $model->contact;
        $post = Yii::$app->request->post();

        if ($contactModel->load($post) && $model->load($post)) {
            if ($model->validate() && $contactModel->save()) { //validate $model BEFORE saving $contactModel
                if ($model->save(false)) { // save(false) bypass validation (already did 2 lines ago)
                    return $this->redirect(['view', 'id' => $contactModel->cont_id]);
                }
            } else {
                throw new \yii\base\ErrorException;
            }
        }
        
        if (!Yii::$app->request->isAjax) {
            return $this->render('update', [
                        'model' => $model,
                        'contactModel' => $contactModel
            ]);
        }
        return $this->renderAjax('update', [
                    'model' => $model,
                    'contactModel' => $contactModel
        ]);
    }
    
    public function actionAddmoreinfos ($contactId) {
        $post = Yii::$app->request->post();
        $model = $this->findModel($contactId);
        if($model->load($post)) {
            if($model->save()&&($this->actionLinkSecteurs($model->cont_id,$post['Rechadminencad']['secteurs']))) {
                return $this->redirect(['view', 'id' => $contactId]);
            }
        } else {
            return $this->renderAjax('_formInfos', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing RechAdminEncad model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the RechAdminEncad model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return RechAdminEncad the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = RechAdminEncad::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    private function actionLinkSecteurs($id, $secteurs) {
        // get all auth_item_child where 'parent' = $role & delete them
        \app\models\Travailler::deleteAll(['cont_id' => $id]);

        if (is_array($secteurs)) {
            foreach ($secteurs as $secteur) {
                $travail = new \app\models\Travailler();
                $travail->cont_id = $id;
                $travail->sect_id = $secteur;
                if (!$travail->save()) {
                    return false;
                }
            }
        }
        return true;
    }    
}

views/rechadminencad/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RechAdminEncad */
/* @var $form yii\widgets\ActiveForm */
    if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert <?php echo Yii::$app->user->getUser()->getIsAdmin()? " alert-warning ": " alert-danger ";?> alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <h5><i class="icon fa fa-times"></i><?php echo Yii::$app->user->getUser()->getIsAdmin()? " Attention !" : " Erreur !"; ?></h5>
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>
<div class="rech-admin-encad-form">

<?php $form = ActiveForm::begin([
        'id' => 'raeForm'
    ]); ?>
    
    <?= $form->field($contactModel, 'cont_civilite')->textInput(['maxlength' => true])->dropDownList(['Mr' => 'Mr' , 'Mme' => 'Mme']) ?>

    <?= $form->field($contactModel, 'cont_nom')->textInput(['maxlength' => true]) ?>
    <?= $form->field($contactModel, 'cont_prenom')->textInput(['maxlength' => true]) ?>


    <?= $form->field($contactModel, 'cont_gsm_principal')->textInput(['maxlength' => true]) ?>
    <?= $form->field($contactModel, 'cont_email_principal')->textInput(['maxlength' => true]) ?>
    
    <?= $form->field($model, 'rae_type')->dropDownList(["1" => "Recherche", "2" => "Administratif", "3" => "Encadrement"]); ?>


    <div class="form-group">
        <?php if (Yii::$app->session->hasFlash('error') && Yii::$app->user->getUser()->getIsAdmin()) echo Html::submitButton($model->isNewRecord ? 'Créer quand même' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 'value' => 'forceAdd', 'name'=>'forceadd']);
              else echo Html::submitButton($model->isNewRecord ? 'Créer' : 'Mettre à jour', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary'])?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rechadminencad/_formInfos.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Contactdivers */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="conso-infos-form">

    <?php $form = ActiveForm::begin([
        'id' => 'reaInfosForm'
    ]); ?>


    <?= $form->field($model, 'secteurs')
        ->dropDownList(yii\helpers\ArrayHelper::map(\app\models\Secteur::find()->all(),'sect_id' , 'sect_nom'),['class' => 'js-multiple' , 'multiple'=>'multiple'])->label('Intérêts') 
    ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Créer' : 'Mettre à jour', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php $this->registerJs("$('.js-multiple').select2();", yii\web\View::POS_READY, 'select2-prod');?>

views/rechadminencad/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RechAdminEncadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="rech-admin-encad-search">

    <?php $form = ActiveForm::begin([
        'action' => 'search',
        'method' => 'get',
    ]); ?>
    <?= $form->field($model, 'contactGSMPrincipalNotNull')->radioList([ 1 => 'Renseigné' , 0 => 'Tous'])->label('Numéro GSM');?>
    <?= $form->field($model, 'contactEmailPrincipalNotNull')->radioList([ 1 => 'Renseigné' , 0 => 'Tous'])->label('Adresse e-mail');?>
    
    <?= $form->field($model, 'rae_type')->checkboxList(['1' =>'Recherche', '2' => 'Administratif', '3' => 'Encadrement']) ?>


    <div class="form-group">
        <?= Html::submitButton('Rechercher', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/rechadminencad/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\RechAdminEncad */

$this->title = 'Ajouter Contact Rech Admin Encad';
$this->params['breadcrumbs'][] = ['label' => 'Rech Admin Encads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rech-admin-encad-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'contactModel' => $contactModel,
    ]) ?>

</div>

views/rechadminencad/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\export\ExportMenu;

/* @var $this yii\web\View */
/* @var $searchModel app\models\RechAdminEncadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$search = Yii::$app->request->pathInfo == 'rechadminencad/search'? true : false;
$this->title = 'Rech Admin Encads';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="rech-admin-encad-index">

    <div id="gridHeader">
        <h1 class="pull-left"><?= Html::encode($this->title) ?></h1>
        <?php if (Yii::$app->user->can('createREA')) : ?>
                <?= Html::a('Ajouter un contact R.E.A.', ['create'], ['class' => 'btn btn-success pull-right']) ?>
        <?php endif; ?>
    </div>
    
    <?php if($search) : ?>
        <div class="x_panel">
            <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        </div>
    <?php endif;?>
    
    <?php if (!$search || Yii::$app->request->get('RechadminencadSearch') != null) : ?>
    <?php $gridColumns = [
//            ['class' => 'yii\grid\SerialColumn'],
                [
                'attribute' => 'contact.cont_civilite',
                'label' => 'Civ',
                'format' => 'text',
                ],
                [
                    'attribute' => 'contactNom',
                    'format' => 'text',
                ],
                'contactPrenom',
                'contactGSMPrincipal',
                'contactEmailPrincipal',
                [
                    'attribute' => 'rae_type',
                    'filter' => array("1" => "Recherche", "2" => "Administratif", "3" => "Encadrement"),
                    'value' => function ($model) {
                        if ($model->rae_type === 1) {
                            return 'Recherche';
                        } elseif ($model->rae_type === 2) {
                            return 'Administratif';
                        } elseif ($model->rae_type === 3) {
                            return 'Encadrement';
                        } else {
                            return 'Non renseignée';
                        }
                    }
                ],
//            'cont_id',
                ['class' => 'kartik\grid\ActionColumn', 'hiddenFromExport' => true ,
                    'buttons' => [
                        'view' => function($url, $model) {
                            $url = \Yii::$app->urlManager->createUrl(['rechadminencad/view', 'id' => $model->cont_id]);
                            return Html::a('<span class="glyphicon glyphicon-eye-open text-info"></span>', $url, ['title' => Yii::t('yii', 'View')]);
                        },
                        'update' => function($url, $model) {
                            if(!\Yii::$app->user->can('createREA')) {
                                return null;
                            }
                            $url = \Yii::$app->urlManager->createUrl(['rechadminencad/update', 'id' => $model->cont_id]);
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['title' => Yii::t('yii', 'Update')]);
                        },
                        'delete' => function($url, $model) {
                            if(!\Yii::$app->user->can('deleteREA')) {
                                return null;
                            }
                            $url = \Yii::$app->urlManager->createUrl(['rechadminencad/delete', 'id' => $model->cont_id]);
                            return Html::a('<span class="glyphicon glyphicon-trash text-danger"></span>', $url, ['title' => Yii::t('yii', 'Delete'), 'data-confirm' => 'Etes vous sûr de vouloir supprimer ce contact?', 'data-method' => 'post']);
                        }
                    ],
                ],
            ] ?>
    <hr />
    <div class="x_panel">
            Exportation :
        <?= ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => $gridColumns,
            'target' => ExportMenu::TARGET_BLANK,
            'exportConfig' => [
                ExportMenu::FORMAT_HTML => false,
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_PDF => false,
                ExportMenu::FORMAT_EXCEL => false
            ],
            'noExportColumns' => [count($gridColumns) - 1]
        ]);?>
    </div>
    
    <div class="x_panel">
        <?=GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $search? null :$searchModel,
            'formatter' => ['class' => 'yii\i18n\Formatter', 'nullDisplay' => '-'],
            'columns' => $gridColumns
        ]);?>
    </div>
    <?php endif; ?>
</div>

views/rechadminencad/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\RechAdminEncad */

$this->title = 'Mise à jour de '. $contactModel->cont_civilite  .' '. $contactModel->cont_nom .' '. $contactModel->cont_prenom;
$this->params['breadcrumbs'][] = ['label' => 'Rech Admin Encads', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $contactModel->cont_nom. ' '. $contactModel->cont_prenom, 'url' => ['view', 'id' => $model->cont_id]];
$this->params['breadcrumbs'][] = 'Mise à jour';
?>
<div class="rech-admin-encad-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'contactModel' => $contactModel,
    ]) ?>

</div>